equation_name: "KdV"
c_0: 0
c_1: 1
c_2: 0.0
c_3: 2.0e-5
c_4: 0.0
xmin: 0
xmax: 1
nx: 256
P: 1
S: 0
E: 1
tmax: 1
dt: 0.001
noise_magnitude: 0.0
initial_condition: "gaussian"
method: "Dealiased_SETDRK4"
Advection_basis_name: "none"
Forcing_basis_name: "none"