Advection_basis_name: none
E: 1
Forcing_basis_name: none
P: 10
S: 9
c_0: 0
c_1: 1
c_2: -0.00390625
c_3: 0.0
c_4: 0.0
dt: 0.0078125
equation_name: Burgers
initial_condition: sin
method: StrangSplit_ETDRK4_SSP33
nx: 256
sigma: 0.001
tmax: 0.5
xmax: 1
xmin: 0
