Advection_basis_name: none
E: 1
Forcing_basis_name: none
P: 0
S: 0
c_0: 0
c_1: 1
c_2: 1
c_3: 0.0
c_4: 1
dt: 0.25
equation_name: Kuramoto-Sivashinsky
ic: Kassam_Trefethen_KS_IC
method: ETDRK4
nx: 256
sigma: 0.001
tmax: 150
xmax: 100.53096491487338
xmin: 0
