Advection_basis_name: constant
E: 1
Forcing_basis_name: none
P: 1
S: 0
c_0: 0
c_1: 1
c_2: 0.0
c_3: 1
c_4: 0.0
dt: 0.0001
ic: traveling_wave
method: SS_ETDRK4_SSP33
nx: 64
sigma: 1
tmax: 1
xmax: 3.141592653589793
xmin: -3.141592653589793
