Advection_basis_name: none
E: 1
Forcing_basis_name: none
P: 1
S: 0
c_0: 0
c_1: 0
c_2: -0.1
c_3: 0.0
c_4: 0.0
dt: 0.0078125
equation_name: Heat
initial_condition: sin
method: Dealiased_SETDRK4
nx: 256
sigma: 0.1
tmax: 16
xmax: 1
xmin: 0
