Advection_basis_name: sin
E: 10
Forcing_basis_name: sin
P: 1
S: 1
c_0: 0
c_1: 1
c_2: 0.0
c_3: 2.0e-05
c_4: 0.0
dt: 0.001
equation_name: KdV
initial_condition: gaussian
method: StrangSplit_ETDRK4_SSP33
nx: 256
sigma: 0.0
tmax: 1
xmax: 1
xmin: 0
