Advection_basis_name: none
E: 2
Forcing_basis_name: none
P: 10
S: 9
c_0: 0.5
c_1: 0
c_2: 0
c_3: 0.0
c_4: 0.0
dt: 0.0078125
equation_name: Linear-Advection
initial_condition: sin
method: StrangSplit_ETDRK4_SSP33
nx: 256
sigma: 0.001
tmax: 16
xmax: 1
xmin: 0
